[build]
    functions="functions/"
    publish="ui/"
    command="go test ./... -v && mkdir functions && go build -o ./functions/signup ./src/functions/signup/signup.go"

[build.environment]
    GO_VERSION="1.16"
    LAMBDA_PRODUCTION="TRUE"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status=200
  force=true